# Generated by Django 4.2.11 on 2024-06-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
